version: 2
jobs:
  build:
    working_directory: ~/doghook
    docker:
      - image: ubuntu:rolling
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update -qq
            apt-get install -y g++ clang-5.0 cmake git wget ssh patchelf
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Generate Make files
          command: |
            chmod +x premake5
            ./premake5 gmake
      - run:
          name: Build
          command: |
            cd premake
            ls /usr/bin/
            ln -s /usr/bin/clang-5.0 /usr/bin/clang
            ln -s /usr/bin/clang++-5.0 /usr/bin/clang++
            make -j2
      - store_artifacts:
          path: ~/dogbook/bin/Debug/libdoghook.so
          destination: libdoghook.so